final/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('taxes.urls')),
    path('admin/', admin.site.urls),
]

taxes/urls.py
from django.urls import path

from . import views

app_name = 'taxes'
urlpatterns = [
    path('', views.display, name='display'),
    path('create/<str:table_name>/', views.create, name='create'),
    path('create/<str:table_name>/verify', views.verify, name='verify'),
    path('update/<str:table_name>/<int:value_id>/', views.update, name='update'),
    path('update/<str:table_name>/<int:value_id>/process/', views.process, name='process'),
    path('delete/<str:table_name>/<int:value_id>/', views.delete, name='delete'),
    path('success/', views.success, name='success'),
]

taxes/models.py
from django.db import models

# Create your models here.


class Taxpayer(models.Model):
    TIN                     = models.IntegerField(unique=True)
    Name                    = models.CharField(max_length=200, blank=True)
    Gender                  = models.CharField(max_length=200, blank=True)
    Civil_Status            = models.CharField(max_length=200, blank=True)
    Birthday                = models.DateField("Birthday", null=True)
    Email                   = models.EmailField(null=True,blank=True)

    def __str__(self):
        return self.TIN

class Business(models.Model):
    SBN                     = models.IntegerField(unique=True)
    Accreditation_Number    = models.IntegerField(null=True, blank=True)
    Facility_Code           = models.CharField(max_length=200, blank=True)


    def __str__(self):
        return self.SBN

class Document(models.Model):
    DLN                     = models.IntegerField(unique=True)
    SBN                     = models.ForeignKey(Business, on_delete='CASCADE') # old
    TIN                     = models.ForeignKey(Taxpayer, on_delete='CASCADE') # new
    Registering_Office      = models.CharField(max_length=200, blank=True)
    BIR_Registration_Date   = models.DateField("BIR Registration Date", null=True)


    def __str__(self):
        return "DLN - {}".format(self.DLN)

taxes/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.template import loader
from .models import Document, Taxpayer, Business 
    

table_models = {
    "Document" : Document, 
    "Taxpayer" : Taxpayer, 
    "Business" : Business,
}

def display(request):
    table_list = [ 
        {   
            'name'      : keyv,
            'fields'    : [f.verbose_name for f in table._meta.fields],
            'row_list'  : [[field.value_to_string(obj) for field in table._meta.fields] for obj in table.objects.order_by(table._meta.fields[1].name)]
        } for keyv, table in table_models.items()
    ]

    join_list = [
        {
            'name' : 'BusinessOwner',
            'fields' : ['temp','TIN', 'Taxpayer Name', 'SBN'],
            'row_list': [['temp', doc.TIN.TIN, doc.TIN.Name, doc.SBN.SBN] for doc in Document.objects.order_by("TIN__TIN", "SBN__SBN")],
        }
    ]
    
    table_list.extend(join_list)


    for table in table_list:
        if table['name'] == "Document":
            table['row_list'] = []
            for i,row in enumerate(Document.objects.order_by("DLN")):

                table['row_list'].append([field.value_to_string(row) for field in Document._meta.fields])
                table['row_list'][i][2] = "{}".format(row.SBN.SBN)
                table['row_list'][i][3] = "{}".format(row.TIN.TIN)

    template = loader.get_template('taxes/display.html')

    context_list = {
        'table_list' : table_list,
        'join_list' : join_list,
    }

    return HttpResponse(template.render(context_list, request))

# Create
def create(request, table_name):
    template = loader.get_template('taxes/create.html')
    context_list = {
        'table_models' : table_models,
        'table_name' : table_name,
    }
    return HttpResponse(template.render(context_list, request))

# Update
def update(request, table_name, value_id):
    try:
        table = table_models[table_name]
    except KeyError:
        raise Http404("Table does not exist")

    obj = table.objects.get(id = value_id)
    fields = table._meta.fields[1:]
    values = { f.name : f.value_to_string(obj) for f in fields}
    context_list = {
        'value_id' : value_id, 
        'values' : values,
        'table_models' : table_models,
        'table_name' : table_name,
    }
    template = loader.get_template('taxes/update.html')
    return HttpResponse(template.render(context_list, request))

# Delete
def delete(request, table_name, value_id):
    table = table_models[table_name]
    value = table.objects.get(id = value_id)
    value.delete()
    return HttpResponseRedirect(reverse('taxes:display'))

# Verify
def verify(request, table_name):
    try:
        table = table_models[table_name]
    except KeyError:
        raise Http404("Table does not exist")

    
    fields = table._meta.fields[1:]
    try:
        init_vals = { f.name : request.POST[f.name] for f in fields }
        if table_name == "Document":
            if request.POST['DLN'] in [d.DLN for d in Document.objects.all()]:
                raise KeyError

            try:
                obj = Taxpayer.objects.get(TIN=init_vals['TIN'])
            except:
                obj = Taxpayer(TIN=init_vals['TIN'])
                obj.save()
            init_vals['TIN'] = obj

            try:
                obj = Business.objects.get(SBN=init_vals['SBN'])
            except:
                obj = Business(SBN=init_vals['SBN'])
                obj.save()
            init_vals['SBN'] = obj

        new_entry = table(**init_vals)
        new_entry.save()
        
        return HttpResponseRedirect(reverse('taxes:display'))
    except:
        template = loader.get_template('taxes/create.html')
        context_list = {
            'table_models' : table_models,
            'table_name' : table_name,
            'error_message' : "{} entry already exists".format(table_name),
        }
        return HttpResponse(template.render(context_list, request))
               


    return HttpResponse("Verify here")

# Successs
def success(request):
    return HttpResponse("Successs here")

def process(request, table_name, value_id):
    try:
        table = table_models[table_name]
    except:
        raise Http404("Table not found")

    fields = table._meta.fields[1:]
    try:
        init_vals = { f.name : request.POST[f.name] for f in fields }
    except:
        template = loader.get_template('taxes/update.html')
        context_list = {
            'table_name' : table_name,
            'value_id' : value_id, 
            'table_models' : table_models,
            'error_message' : ' '.join([f.name for f in fields if f.name not in request.POST]),
        }
        return HttpResponse(template.render(context_list, request))
    else:
        table.objects.filter(id = value_id).update(**init_vals)
        return HttpResponseRedirect(reverse('taxes:display'))


    return HttpResponse("Verify here")

taxes/templates/taxes/create.html
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>CS 165 Phase 4</title>
</head>

<body>


{% if table_name in table_models %}
    <div class="container col-md-4">
        {% if error_message %}
            <p><strong> {{ error_message }} </strong></p>
        {% endif %}
        <form action="{% url 'taxes:verify' table_name %}" method="post">
            {% csrf_token %}

            {% if table_name == "Document" %}

                <div class="form-group">
                    <label for="DLN"> DLN: </label>
                    <input class="form-control" id="DLN" type="number" min="1" name="DLN">
                </div>

                <div class="form-group">
                    <label for="SBN"> SBN: </label>
                    <input class="form-control" id="SBN" type="number" min="1" name="SBN">
                </div>

                <div class="form-group">
                    <label for="TIN"> TIN: </label>
                    <input class="form-control" id="TIN" type="number" min="1" name="TIN">
                </div>

                <div class="form-group">
                    <label for="Registering Office"> Registering Office: </label>
                    <input class="form-control" id="Registering Office" type="text" name="Registering_Office">
                </div>

                <div class="form-group">
                    <label for="BIR"> BIR Registration Date: </label>
                    <input class="form-control" id="BIR" type="date" name="BIR_Registration_Date">
                </div>

                

            {% elif table_name == "Taxpayer" %}
                <div class="form-group">
                    <label for="TIN"> TIN: </label>
                    <input class="form-control" id ="TIN" type="number" min="1" name="TIN">
                </div>

                <div class="form-group">
                    <label for="Name"> Name: </label>
                    <input class="form-control" id="Name" type="text" name="Name">
                </div>

                <div class="form-group">
                    <label class="control-label"> Gender: </label> <br>
                            
                    <label class="radio-inline"> 
                        <input type="radio" id="Male" name="Gender" value="Male"> 
                            Male
                    </label>

                    <label class="radio-inline">
                        <input type="radio" id="Female" name="Gender" value="Female">
                            Female
                    </label>

                    <label class="radio-inline">
                        <input type="radio" id="Other" name="Gender" value="Other">
                            Other
                    </label>

                </div>

                        
                <div class="form-group">
                    <label class="control-label"> Civil Status: </label> <br>
                    <label class="radio-inline">
                        <input  type="radio" name="Civil_Status" id="Single" value="Single">
                        Single
                    </label>

                    <input  type="radio" name="Civil_Status" id="Married" value="Married">
                        <label class="radio-inline">
                        Married
                    </label>
                </div>
                                

                <div class="form-group">
                    <label for="Birthday"> Birthday: </label>
                    <input class="form-control" id="Birthday" type="date" name="Birthday">
                </div>

                <div class="form-group">
                    <label for="Email"> Email: </label>
                    <input class="form-control" id="Email" type="email" name="Email">
                </div>

            {% elif table_name == "Business" %}
                <div class="form-group">
                    <label for="SBN"> SBN: </label>
                    <input class="form-control" id ="SBN" type="number" min="1" name="SBN">
                </div>

                <div class="form-group">
                    <label for="Accreditation Number"> Accreditation Number: </label>
                    <input class="form-control" id ="Accreditation Number" type="number" min="1" name="Accreditation_Number">
                </div>

                <div class="form-group">
                    <label for="fc"> Facility Code: </label>
                    <input class="form-control" id="fc" type="text" name="Facility_Code">
                </div>
            {% endif %}
            <div class="form-group">
                <input class="form-control btn btn-info" type="submit" class="btn btn-info" value="Submit">
            </div>

            <div class="form-group">
                <a class="btn btn-danger form-control" href="{% url 'taxes:display' %}" align="center">
                    Back
                </a>
            </div>
        </form>

    {% else %}
        <p> {{ table_name }} table does not exist </p>
    {% endif %}

</div>
</body>

taxes/templates/taxes/display.html
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>CS 165 Phase 4</title>
</head>

<body>
{% for table in table_list %}

    <div class="container">
        <h1 align="center"> <strong> {{ table.name }} </strong> </h1>
        <table align="center" class="table table-striped table-bordered">
            <tr>
            {% for fname in table.fields %}
                {% if forloop.counter != 1 %}
                    <th> {{ fname }} </th>
                {% endif %}
            {% endfor %}


                {% if table not in join_list %}
                    <td align="center">
                        <a href="{% url 'taxes:create' table.name %}">
                            Add New {{ table.name }}
                        </a>
                    </td>
                {% endif %}
            </tr>

            {% for row in table.row_list %}
            <tr>
                {% for value in row %}
                    {% if forloop.counter != 1 %}
                    <td> {{ value }} </td>
                    {% endif %}
                {% endfor %}

                {% if table not in join_list %}
                    <td align="center">
                        <a href="{% url 'taxes:update' table.name row.0 %}">
                            Update
                        </a> <br>
                        <a href="{% url 'taxes:delete' table.name row.0 %}">
                            Delete
                        </a> <br>
                    </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
    <br>
{% endfor %}


</body>

taxes/templates/taxes/update.html
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>CS 165 Phase 4</title>
</head>

<body>


{% if table_name in table_models %}
    <div class="container col-md-4">
        {% if error_message %}
            <p><strong> {{ error_message }} </strong></p>
        {% endif %}
        <form action="{% url 'taxes:process' table_name value_id %}" method="post">
            {% csrf_token %}

            {% if table_name == "Document" %}

                <div class="form-group">
                    <label for="DLN"> DLN: </label>
                    <input class="form-control" id="DLN" type="number" min="1" name="DLN" value="{{ values.DLN }}" readonly>
                </div>

                <div class="form-group">
                    <label for="SBN"> SBN: </label>
                    <input class="form-control" id="SBN" type="number" min="1" name="SBN" value="{{ values.SBN }}" readonly>
                </div>

                <div class="form-group">
                    <label for="TIN"> TIN: </label>
                    <input class="form-control" id="TIN" type="number" min="1" name="TIN" value="{{ values.TIN }}" readonly>
                </div>

                <div class="form-group">
                    <label for="Registering Office"> Registering Office: </label>
                    <input class="form-control" id="Registering Office" type="text" name="Registering_Office" value="{{ values.Registering_Office }}">
                </div>

                <div class="form-group">
                    <label for="BIR"> BIR Registration Date: </label>
                    <input class="form-control" id="BIR" type="date" name="BIR_Registration_Date" value="{{ values.BIR_Registration_Date }}">
                </div>

                

            {% elif table_name == "Taxpayer" %}
                <div class="form-group">
                    <label for="TIN"> TIN: </label>
                    <input class="form-control" id ="TIN" type="number" min="1" name="TIN"  value="{{ values.TIN }}" readonly>
                </div>

                <div class="form-group">
                    <label for="Name"> Name: </label>
                    <input class="form-control" id="Name" type="text" name="Name" value="{{ values.Name }}">
                </div>

                <div class="form-group">
                    <label class="control-label"> Gender: </label> <br>
                            
                    <label class="radio-inline"> 
                        <input type="radio" id="Male" name="Gender" value="Male" {% if values.Gender == 'Male'%} checked {% endif %}> 
                            Male
                    </label>

                    <label class="radio-inline">
                        <input type="radio" id="Female" name="Gender" value="Female" {% if values.Gender == 'Female'%} checked {% endif %}>
                            Female
                    </label>

                    <label class="radio-inline">
                        <input type="radio" id="Other" name="Gender" value="Other" {% if values.Gender == 'Other'%} checked {% endif %}>
                            Other
                    </label>

                </div>

                        
                <div class="form-group">
                    <label class="control-label"> Civil Status: </label> <br>
                    <label class="radio-inline">
                        <input  type="radio" name="Civil_Status" id="Single" value="Single" {% if values.Civil_Status == 'Single'%} checked {% endif %}>
                        Single
                    </label>

                    <input  type="radio" name="Civil_Status" id="Married" value="Married" {% if values.Civil_Status == 'Married'%} checked {% endif %}>
                        <label class="radio-inline">
                        Married
                    </label>
                </div>
                                

                <div class="form-group">
                    <label for="Birthday"> Birthday: </label>
                    <input class="form-control" id="Birthday" type="date" name="Birthday" value="{{ values.Birthday }}">
                </div>

                <div class="form-group">
                    <label for="Email"> Email: </label>
                    <input class="form-control" id="Email" type="email" name="Email" value="{{ values.Email }}">
                </div>

            {% elif table_name == "Business" %}
                <div class="form-group">
                    <label for="SBN"> SBN: </label>
                    <input class="form-control" id ="SBN" type="number" min="1" name="SBN" value="{{ values.SBN }}" readonly>
                </div>

                <div class="form-group">
                    <label for="Accreditation Number"> Accreditation Number: </label>
                    <input class="form-control" id ="Accreditation Number" type="number" min="1" name="Accreditation_Number" value="{{ values.Accreditation_Number }}">
                </div>

                <div class="form-group">
                    <label for="fc"> Facility Code: </label>
                    <input class="form-control" id="fc" type="text" name="Facility_Code" value="{{ values.Facility_Code }}">
                </div>
            {% endif %}
            <div class="form-group">
                <input class="form-control btn btn-info" type="submit" class="btn btn-info" value="Submit">
            </div>

            <div class="form-group">
                <a class="btn btn-danger form-control" href="{% url 'taxes:display' %}" align="center">
                    Back
                </a>
            </div>
        </form>

    {% else %}
        <p> {{ table_name }} table does not exist </p>
    {% endif %}

    </div>
</body>